#! /bin/sh

#bspc monitor -d I II III IV V VI VII VIII IX
bspc monitor VGA-0 -d I II III
bspc monitor DVI-D-0 -d IV V VI
bspc monitor HDMI-0 -d VII VIII IX

bspc config left_padding        -6
bspc config right_padding       -6
bspc config bottom_padding      -6

bspc config border_width        2
bspc config window_gap          10
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config normal_border_color "#314D4E"
bspc config active_border_color "#346E71"
bspc config focused_border_color "#439545"
bspc config urgent_border_color "#B1C97E"

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Screenkey manage=off

compton -CG &
nm-applet &
nitrogen --restore &
trayer --edge top --align left --margin 400 --monitor primary --SetDockType true --widthtype request --transparent true --height 16 &
panel &
