#! /bin/sh
#
# Example panel for LemonBoy's bar

COLOR_FOREGROUND='#A3A6AB'
COLOR_BACKGROUND='#34322E'
COLOR_FOCUSED_OCCUPIED_FG='#F6F9FF'
COLOR_FOCUSED_OCCUPIED_BG='#5C5955'
COLOR_FOCUSED_FREE_FG='#F6F9FF'
COLOR_FOCUSED_FREE_BG='#6D561C'
COLOR_FOCUSED_URGENT_FG='#34322E'
COLOR_FOCUSED_URGENT_BG='#F9A299'
COLOR_OCCUPIED_FG='#A3A6AB'
COLOR_OCCUPIED_BG='#34322E'
COLOR_FREE_FG='#6F7277'
COLOR_FREE_BG='#34322E'
COLOR_URGENT_FG='#F9A299'
COLOR_URGENT_BG='#34322E'
COLOR_LAYOUT_FG='#A3A6AB'
COLOR_LAYOUT_BG='#34322E'
COLOR_TITLE_FG='#A3A6AB'
COLOR_TITLE_BG='#34322E'
COLOR_STATUS_FG='#A3A6AB'
COLOR_STATUS_BG='#34322E'

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys_infos="%{ F$COLOR_STATUS_FG B$COLOR_BACKGROUND} ${line#?}"
			;;
		T*)
			# xtitle output
			title="%{ F$COLOR_TITLE_FG B$COLOR_BACKGROUND} ${line#?}"
			;;
		V*)
			# volume output
			volume="%{ F$COLOR_STATUS_FG B$COLOR_BACKGROUND}Vol: ${line#?}%"
			;;
		M*)
			# memory output
			memory="%{ F$COLOR_STATUS_FG B$COLOR_STATUS_BG}Mem: ${line#?}%"
			;;
		L*)
			# load output
			load="%{ F$COLOR_STATUS_FG B$COLOR_STATUS_BG}Load: ${line#?}"
			;;
		B*)
			# battery output
			battery="%{ F$COLOR_STATUS_FG B$COLOR_STATUS_BG}Bat: ${line#?}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					O*)
						# focused occupied desktop
						wm_infos="$wm_infos %{U$COLOR_FOCUSED_OCCUPIED_FG B$COLOR_FOCUSED_OCCUPIED_BG +u} ${name} %{-uB$COLOR_BACKGROUND}"
						;;
					F*)
						# focused free desktop
						wm_infos="$wm_infos %{U$COLOR_FOCUSED_FREE_FG B$COLOR_FOCUSED_FREE_BG +u} ${name} %{-uB$COLOR_BACKGROUND}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="$wm_infos %{U$COLOR_FOCUSED_URGENT_FG B$COLOR_FOCUSED_URGENT_BG +u} ${name }%{-uB$COLOR_BACKGROUND}"
						;;
					o*)
						# occupied desktop
						wm_infos="$wm_infos %{F$COLOR_OCCUPIED_FG B$COLOR_OCCUPIED_BG} ${name} %{B$COLOR_BACKGROUND}"
						;;
					f*)
						# free desktop
						wm_infos="$wm_infos %{F$COLOR_FREE_FG B$COLOR_FREE_BG} ${name} %{B$COLOR_BACKGROUND}"
						;;
					u*)
						# urgent desktop
						wm_infos="$wm_infos %{F$COLOR_URGENT_FG B$COLOR_URGENT_BG} ${name} %{B$COLOR_BACKGROUND}"
						;;
					L*)
						# layout
						layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
						wm_infos="$wm_infos    %{F$COLOR_LAYOUT_FG B$COLOR_LAYOUT_BG} $layout"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l} $wm_infos %{c} $title %{r} $volume | $battery | $memory | $load | $sys_infos"
done
