#! /bin/sh
#
# Example panel for LemonBoy's bar

COLOR_FOREGROUND='#FFdddddd'
COLOR_BACKGROUND='#FF101010'
COLOR_FOCUSED_OCCUPIED_FG='#FFdddddd'
COLOR_FOCUSED_OCCUPIED_BG='#FF404040'
COLOR_FOCUSED_FREE_FG='#FFdddddd'
COLOR_FOCUSED_FREE_BG='#FF101010'
COLOR_FOCUSED_URGENT_FG='#FFdddddd'
COLOR_FOCUSED_URGENT_BG='#FFe84f4f'
COLOR_OCCUPIED_FG='#FFdddddd'
COLOR_OCCUPIED_BG='#FF404040'
COLOR_FREE_FG='#FF555555'
COLOR_FREE_BG='#FF101010'
COLOR_URGENT_FG='#FFdddddd'
COLOR_URGENT_BG='#FFd23d3d'
COLOR_LAYOUT_FG='#FFdddddd'
COLOR_LAYOUT_BG='#FF101010'
COLOR_TITLE_FG='#FF555555'
COLOR_TITLE_BG='#FF101010'
COLOR_STATUS_FG='#FFdddddd'
COLOR_STATUS_BG='#FF101010'

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys_infos="%{ F$COLOR_STATUS_FG B$COLOR_BACKGROUND} ${line#?}"
			;;
		T*)
			# xtitle output
			title="%{ F$COLOR_TITLE_FG B$COLOR_BACKGROUND} ${line#?}"
			;;
		V*)
			# volume output
			volume="%{ F$COLOR_STATUS_FG B$COLOR_BACKGROUND}Vol: ${line#?}%"
			;;
		M*)
			# memory output
			memory="%{ F$COLOR_STATUS_FG B$COLOR_STATUS_BG}Mem: ${line#?}%"
			;;
		L*)
			# load output
			load="%{ F$COLOR_STATUS_FG B$COLOR_STATUS_BG}Load: ${line#?}"
			;;
		B*)
			# battery output
			battery="%{ F$COLOR_STATUS_FG B$COLOR_STATUS_BG}Bat: ${line#?}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					O*)
						# focused occupied desktop
						wm_infos="$wm_infos %{F$COLOR_FOCUSED_OCCUPIED_FG U$COLOR_FOCUSED_OCCUPIED_FG B$COLOR_FOCUSED_OCCUPIED_BG +u} ${name} %{-uB$COLOR_BACKGROUND}"
						;;
					F*)
						# focused free desktop
						wm_infos="$wm_infos %{F$COLOR_FOCUSED_FREE_FG U$COLOR_FOCUSED_FREE_FG B$COLOR_FOCUSED_FREE_BG +u} ${name} %{-uB$COLOR_BACKGROUND}"
						;;
					U*)
						# focused urgent desktop
						wm_infos="$wm_infos %{F$COLOR_FOCUSED_URGENT_FG U$COLOR_FOCUSED_URGENT_FG B$COLOR_FOCUSED_URGENT_BG +u} ${name} %{-uB$COLOR_BACKGROUND}"
						;;
					o*)
						# occupied desktop
						wm_infos="$wm_infos %{F$COLOR_OCCUPIED_FG B$COLOR_OCCUPIED_BG} ${name} %{B$COLOR_BACKGROUND}"
						;;
					f*)
						# free desktop
						wm_infos="$wm_infos %{F$COLOR_FREE_FG B$COLOR_FREE_BG} ${name} %{B$COLOR_BACKGROUND}"
						;;
					u*)
						# urgent desktop
						wm_infos="$wm_infos %{F$COLOR_URGENT_FG B$COLOR_URGENT_BG} ${name} %{B$COLOR_BACKGROUND}"
						;;
					L*)
						# layout
						layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
						wm_infos="$wm_infos    %{F$COLOR_LAYOUT_FG B$COLOR_LAYOUT_BG} $layout"
						;;
				esac
				shift
			done
			;;
	esac
	 printinfo="%{l} $wm_infos %{c} $title %{r} $volume | $memory | $load | $sys_infos"
	 printf "%s\n" "%{S0}$printinfo%{S1}$printinfo%{S2}$printinfo"
done
