#!/bin/sh
while true
do
    volume_info=`/usr/bin/pulseaudio-ctl | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"`
    mute=$(echo "$volume_info" | grep 'Is sink muted' | awk '{ printf "%s", $5 }')
    level=$(echo "$volume_info" | grep 'Volume level' | awk "{ if (\"$mute\" == \"no\") { printf \"%s%\", \$4 } else { printf \"mute\" } }")

    echo "V$level"
    sleep 5
done
