#! /bin/sh

#bspc monitor -d I II III IV V VI VII VIII IX
bspc monitor VGA1 -d IV V VI
bspc monitor HDMI1 -d I II III
bspc monitor HDMI2 -d VII VIII IX

bspc config border_width        2
bspc config window_gap          10
bspc config top_padding 				-10
bspc config bottom_padding			-10
bspc config left_padding				-10
bspc config right_padding				-10
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config normal_border_color "#314D4E"
bspc config active_border_color "#346E71"
bspc config focused_border_color "#439545"
bspc config urgent_border_color "#B1C97E"

bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
bspc rule -a Screenkey manage=off

compton -CG &
nm-applet &
nitrogen --restore &
trayer --edge top --align right --monitor primary --SetDockType true --SetPartialStrut true --expand true --widthtype request --transparent true --tint 0x191970 --height 16 &
/home/zettazete/.config/bspwm/panel/panel &
