#! /bin/sh

#bspc monitor -d I II III IV V VI VII VIII IX
bspc monitor VGA1 -d III VI IX
bspc monitor HDMI1 -d I IV VII
bspc monitor HDMI2 -d II V VIII

bspc config border_width        2
bspc config window_gap          5
bspc config top_padding					12
bspc config bottom_padding			-5
bspc config left_padding				-5
bspc config right_padding				-5
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a Screenkey manage=off

panel &
